pretrained_model_path: models/StableDiffusion/
output_dir: models/Motion_Module/bunny
train_data:
  video_path: data/bunny.mp4
  prompt: 
  - view down from sky to grass
  n_sample_frames: 16
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 1
validation_data:
  prompts:
  - view down from sky to grass
  video_length: 16
  width: 512
  height: 512
  num_inference_steps: 25
  temporal_context: 64
  guidance_scale: 8
  use_inv_latent: true
  num_inv_steps: 40
validation_steps: 10000
train_whole_module: false
trainable_modules:
- to_q
train_batch_size: 1
max_train_steps: 1000
learning_rate: 0.0045
scale_lr: false
lr_scheduler: cosine
lr_warmup_steps: 10
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.08
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
gradient_accumulation_steps: 1
gradient_checkpointing: true
checkpointing_steps: 100
start_global_step: 0
resume_from_checkpoint: null
mixed_precision: fp16
use_8bit_adam: false
enable_xformers_memory_efficient_attention: true
seed: 33
motion_module: models/Motion_Module/mm_sd_v15.ckpt
inference_config_path: configs/inference/inference.yaml
motion_module_pe_multiplier: 1
dataset_class: MultiTuneAVideoDataset
